### ISSUE TITLE
Why use sigmoid instead of softmax in relation classification?

### ISSUE THREAD

**Issue by Maybewuss** [markus-eberts/spert#10]
Does a pair of candidates have more than one relations?

**Comment by markus-eberts** [comment]
Our intention was indeed to be able to handle such cases with our model (e.g. "John Doe lives and works in New York City" with (John Doe, Lives_In, New York City) and (John Doe, Works_In, New York City)).
However, in the datasets we evaluated in our paper a pair of entities is annotated with a single relation at most. So in this case you can probably achieve similar results by using a softmax function. But at the end our goal is to create a model that is universally applicable and not specifically designed for the available academic data.

**Comment by markus-eberts** [comment]
Please leave a comment if this issue is still unsolved.
