### ISSUE TITLE
Simplified list of entities and relations

### ISSUE THREAD

**Issue by demongolem** [markus-eberts/spert#12]
When using store_examples = true, I get all the html output in the log directory.  Whereas this is very nice for visualization, it is not so nice to use the results for other tasks or for further portions of a custom pipeline.  Is there an option currently to get the list of entities and relations predicted with their start and end tokens (or character offsets) in a text file?

**Comment by markus-eberts** [comment]
Thanks for your suggestion! Predictions are now stored in the log directory if 'store_predictions' is set to 'true' in the configuration file (commit 8d709190513cc932197d44715bbe8384b4c00c1c). We store the predictions in the same JSON format as the ground truth dataset. Does this work for you?

**Comment by markus-eberts** [comment]
Please leave a comment if this issue is still unsolved.

**Comment by demongolem** [comment]
It does do as needed, thanks.
