### ISSUE TITLE
Sample code working on Mac OS not working on Ubuntu 18-04

### ISSUE THREAD

**Issue by demongolem** [markus-eberts/spert#13]
I had everything working on Mac OS and I moved over the folder to Ubuntu.  I get the following error when I try to run`python ./spert.py eval --config configs/example_eval.conf:`

> torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
> Process SpawnProcess-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/greg/spert/spert.py", line 23, in __eval
>     input_reader_cls=input_reader.JsonInputReader)
>   File "/home/greg/spert/spert/spert_trainer.py", line 165, in eval
>     self._eval(model, input_reader.get_dataset(dataset_label), input_reader)
>   File "/home/greg/spert/spert/spert_trainer.py", line 233, in _eval
>     for batch in tqdm(sampler, total=total, desc='Evaluate epoch %s' % epoch):
>   File "/home/greg/.local/lib/python3.6/site-packages/tqdm/std.py", line 1104, in __iter__
>     for obj in iterable:
>   File "/home/greg/spert/spert/sampling.py", line 155, in __next__
>     batch, _ = self._results.next()
>   File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
>     raise value
> multiprocessing.pool.MaybeEncodingError: Error sending result: '(<spert.sampling.EvalTensorBatch object at 0x7f89949bfa20>, 0)'. Reason: 'RuntimeError('error executing torch_shm_manager at "/usr/local/lib/python3.6/dist-packages/torch/bin/torch_shm_manager" at /pytorch/torch/lib/libshm/core.cpp:99',)

**Comment by markus-eberts** [comment]
Do you have the PyTorch version installed that matches with the CUDA version on the Ubuntu system? In case you don't have CUDA installed on your system or no compatible GPU is available, is is important that you install the CPU only version of PyTorch. See https://pytorch.org/ for further instructions (under 'Quick Start Locally'), e.g. by selecting 'CUDA=None'.

**Comment by demongolem** [comment]
Yes that helped, thanks.  I uninstalled pytorch and installed a cpu version and was able to successfully run the same code.
