### ISSUE TITLE
A little puzzle

### ISSUE THREAD

**Issue by DragonAndSky** [markus-eberts/spert#16]
I have a question, where can I get the entity_mask if I predict the relationship between entities from an unmarked sentence

**Comment by markus-eberts** [comment]
Hi,
the term 'entity_mask' in our code is a bit misleading. Better read it as 'entity candidate masks'. During training, this tensor contains masks for all annotated entities and a set of random spans not labelled as an entity as negative samples. During evaluation, where we don't know the entities, 'entity_masks' contains the masks for all spans up to a predefined length (10 in our paper). So when you want to predict relations for an unmarked sentence, you can use the 'create_eval_sample' in 'sampling.py' to get the necessary tensors, including 'entity_masks'.

**Comment by DragonAndSky** [comment]
Thanks, i understanded.
