### ISSUE TITLE
Selecting Span Problem

### ISSUE THREAD

**Issue by Jim0530** [markus-eberts/spert#21]
I've seen ur paper.For one thing I don't really understand is how do u or what is ur algorithm select spans from a sentence and using as ur input to the span classifier?
And for relation classifier is it possible to convert into open relation extraction which relation r not pre-defined and exist int the sentence?

**Comment by avipartho** [comment]
My understanding from the code is that during training the system generates all spans from the inputs and then does some sampling from that. During inference/evaluation, however, it selects spans based on how the model is prioritizing the spans i.e. what has it learned through the training. The authors might confirm this.

**Comment by markus-eberts** [comment]
Thanks for answering this issue @avipartho. You are right, during inference we are classifying all spans up to length 10 (this is a hyperparameter - you can adjust it in the config file). All spans assigned to the 'None' class are then filtered.
