### ISSUE TITLE
early stopping

### ISSUE THREAD

**Issue by CamillaBressan** [markus-eberts/spert#28]
Dear authors, 

First of all thank you so much for your well done work. The code is really well written and I was able to reproduce the results of the paper and also work on my data. 
I was wondering if there is the possibility of switching on a sort of early stopping mechanism, in order to stop the training only when the performance over the development set gets significantly worse than the one over the training set. Is there a particular input argument I should specify to allow for it or does it need to be implemented?

Thanks so much for your time and Best,

**Comment by markus-eberts** [comment]
Hi,
early stopping is not implemented and I'm also not planning on adding it. Feel free to make a pull request in case you implemented it yourself.
