### ISSUE TITLE
How to do predict?

### ISSUE THREAD

**Issue by liutianling** [markus-eberts/spert#29]
Thanks for your good work.
I want to know the format of input of predict?
It's like this: (1)
Jack is born in London.
or like this: (2)
where   O   ['N']  
the O   ['N']   
government  O   ['N']   
soldiers    O   ['N']   
with    O   ['N']   
the O   ['N']   
former  O   ['N']   
Northern    B-Org   ['N']   
Improvement I-Org   ['N']   [
Brigade I-Org   
 (   O   ['N']   
 Brigada B-Org   ['N']  
 de  I-Org   ['N']   
Melhoramentos   I-Org   ['N']   
do  I-Org   ['N']   
 Norte   I-Org   
  )   O   ['N']   
  ,   O   ['N']

**Comment by ChloeJKim** [comment]
@liutianling 
Hi, I'm also trying to run prediction as well, what steps did you follow to do prediction? and what was the format of input data, can you let me know?
Thanks in advance
