### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by CamillaBressan** [markus-eberts/spert#33]
Dear authors, 

I was wondering if you could provide a license for your project (or point me to that if there's already an existing one), to clarify if and under which conditions the code can be used and integrated in other projects. (https://choosealicense.com/no-permission/)

Thanks and Best,

**Comment by markus-eberts** [comment]
Hi,

I just added a license (commit b9228203c3fc737b2606ec1c09d84f47486e86dc).
