### ISSUE TITLE
How can I get the file 'vocab.txt'?

### ISSUE THREAD

**Issue by ZengYoufeng** [markus-eberts/spert#4]
Hello, I want to perform experiments on my own dataset, but I cannot find the file 'vocab.txt'. How can I get this file?

**Comment by markus-eberts** [comment]
Hi ZengYoufeng,
the corresponding vocabulary file is already included for the models we trained on the CoNLL04, ADE and SciERC datasets (under "./data/models" after executing "./scripts/fetch_models.sh"). If you want to train a model from-scratch, you should have a look at the "transformers" (https://github.com/huggingface/transformers) library we are using. You can either specify one of the pre-trained BERT models included in "transformers" as both the "model_path" and "tokenizer_path" (e.g. "bert-base-cased" as in "configs/example_train.conf") or point "model_path" and "tokenizer_path" to a directory that contains model weights or a vocabulary file respectively.

**Comment by ZengYoufeng** [comment]
Thanks for your answer, I have got the trained model 'pytorch_model.bin' with self-built dataset, but I cannot execute the command 'python ./spert.py eval --config configs/example_eval.conf' successfully due to the lack of the file 'vocab.txt'. Now I want to know how to generate a vocabulary file that fits self-built dataset for evaluation. Hope you can give me some detailed guidance, I will be grateful!

**Comment by ZengYoufeng** [comment]
> Hi ZengYoufeng,
> the corresponding vocabulary file is already included for the models we trained on the CoNLL04, ADE and SciERC datasets (under "./data/models" after executing "./scripts/fetch_models.sh"). If you want to train a model from-scratch, you should have a look at the "transformers" (https://github.com/huggingface/transformers) library we are using. You can either specify one of the pre-trained BERT models included in "transformers" as both the "model_path" and "tokenizer_path" (e.g. "bert-base-cased" as in "configs/example_train.conf") or point "model_path" and "tokenizer_path" to a directory that contains model weights or a vocabulary file respectively.

Thanks for your answer, I have got the trained model 'pytorch_model.bin' with self-built dataset, but I cannot execute the command 'python ./spert.py eval --config configs/example_eval.conf' successfully due to the lack of the file 'vocab.txt'. Now I want to know how to generate a vocabulary file that fits self-built dataset for evaluation. Hope you can give me some detailed guidance, I will be grateful!

**Comment by markus-eberts** [comment]
Did you train your own model on the self-built dataset or where is 'pytorch_model.bin' from? You should use the same 'vocab.txt' file that was used to train 'pytorch_model.bin'.

**Comment by ZengYoufeng** [comment]
> Did you train your own model on the self-built dataset or where is 'pytorch_model.bin' from? You should use the same 'vocab.txt' file that was used while training 'pytorch_model.bin'.

I have trained my own model on the self-built dataset on the same training settings of the CoNLL04 dataset. Then, I got three files, 'pytorch_model.bin', 'config.json' and 'extra.state', respectively. However, I can't find the file 'vocab.txt'. Therefore, I cannot execute the command 'python ./spert.py eval --config configs/example_eval.conf'.

**Comment by markus-eberts** [comment]
You should use the same 'vocab.txt' file that was used during training. In your case, this is probably the one located in 'data/models/conll04'. So just set 'tokenizer_path' in 'example_eval.conf' to point to 'data/models/conll04'.

**Comment by illcat** [comment]
> > Did you train your own model on the self-built dataset or where is 'pytorch_model.bin' from? You should use the same 'vocab.txt' file that was used while training 'pytorch_model.bin'.
> 
> I have trained my own model on the self-built dataset on the same training settings of the CoNLL04 dataset. Then, I got three files, 'pytorch_model.bin', 'config.json' and 'extra.state', respectively. However, I can't find the file 'vocab.txt'. Therefore, I cannot execute the command 'python ./spert.py eval --config configs/example_eval.conf'. I want to know how to get the file 'vocab.txt' that fits self-built dataset.

Please refer to the use of huggingface/transformers!!!!!!

**Comment by ZengYoufeng** [comment]
I understand that the file 'vocab.txt' is related to the language representation model, not to the dataset. I observed that the vocabulary files corresponding to the three datasets were different, so I misunderstood that the vocabulary file corresponds to the dataset and was generated by it. I'm so sorry for the misunderstanding and thank you very much for your kind help.

**Comment by markus-eberts** [comment]
No need to be sorry, I'm glad I could help you. The vocabulary files differ because we used SciBERT, which is accompanied by its own vocabulary, instead of BERT-Base-Cased for the SciERC dataset. The ADE and CoNLL04 models were trained using the same BERT-Base-Cased vocabulary.
