### ISSUE TITLE
Conll04 dataset

### ISSUE THREAD

**Issue by NeroL29** [markus-eberts/spert#41]
hi @markus-eberts ,
I was just wondering where I can get the original dataset of Conll04, the link is not mentioned in the original paper

**Comment by markus-eberts** [comment]
Hi,
the original dataset paper should be this one by Roth et al. (-> https://www.aclweb.org/anthology/W04-2401.pdf). The original dataset is available here: https://cogcomp.seas.upenn.edu/page/resource_view/43. We use the joint split of Gupta et al. (->https://www.aclweb.org/anthology/C16-1239.pdf), which is commonly used for joint entity and relation extraction.

**Comment by NeroL29** [comment]
@markus-eberts I found that this data set is the internal data of the University of Pennsylvania. I am a Chinese graduate student and cannot access this webpage. I know this is a copyrighted data. Can you tell me how to get this data set? We consider paying its copyright fees to use it legally.

**Comment by markus-eberts** [comment]
Sorry, I can't help you with that. You should consider to write an email to the University of Pennsylvania or the authors of the original paper (Roth et al.).
