### ISSUE TITLE
Parts of entities are recognised separately

### ISSUE THREAD

**Issue by maiiabocharova** [markus-eberts/spert#58]
Hello, can you please help me with advice how can I solve this issue: trained SpERT on my custom dataset and am getting most of the entities right, but there is this strange repetition with parts of the entities.
Maybe there is some way to solve it. (Didn't have such an issue with huggingface transformers for token classification)
                     {"type": "3.2_mixtures/components/concentration/value", "start": 82, "end": 86}, 
                     {"type": "3.2_mixtures/components/concentration/value", "start": 82, "end": 87}, 
                     {"type": "3.2_mixtures/components/concentration/value", "start": 82, "end": 88}, 
                     {"type": "3.2_mixtures/components/concentration/value", "start": 83, "end": 87}, 
                     {"type": "3.2_mixtures/components/concentration/value", "start": 83, "end": 88}, 
                     {"type": "3.2_mixtures/components/concentration/value", "start": 84, "end": 87}, 
                     {"type": "3.2_mixtures/components/concentration/value", "start": 84, "end": 88}, 
                     {"type": "3.2_mixtures/components/concentration/value", "start": 85, "end": 87}, 
                     {"type": "3.2_mixtures/components/concentration/value", "start": 85, "end": 88}, 
                     {"type": "3.2_mixtures/components/concentration/value", "start": 86, "end": 88},

**Comment by markus-eberts** [comment]
Hi, are there any control characters in your input sentence (e.g. \n)? Could you please send me the corresponding sentence?

**Comment by markus-eberts** [comment]
We had a conversation by email. Please leave a comment if the issue is still relevant.
