### ISSUE TITLE
How to load pre-trained checkpoint in the training

### ISSUE THREAD

**Issue by jmlongriver** [markus-eberts/spert#7]
should I use the folder of checkpoint to fit the "model_path" value in config files?

**Comment by markus-eberts** [comment]
We are passing the value of 'model_path' to the HuggingFace Transformers library (link: https://github.com/huggingface/transformers). To use a pre-trained checkpoint, you can either specify the name of one of the online available models (such as 'bert-base-cased') or the path to a directory containing a model checkpoint. Please see the Transformers library for further details.
