### ISSUE TITLE
error when do evaluating dev in training procedure

### ISSUE THREAD

**Issue by jmlongriver** [markus-eberts/spert#8]
Process SpawnProcess-1:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/*/spert/spert/sampling.py", line 253, in _produce_eval_batch
    sample = _create_eval_sample(d, max_span_size, context_size)
  File "/*/spert/spert/sampling.py", line 403, in _create_eval_sample
    entity_masks = torch.stack(entity_masks)
RuntimeError: stack expects a non-empty TensorList
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/media/work/aads_nlp/spert/spert.py", line 12, in __train
    types_path=run_args.types_path, input_reader_cls=input_reader.JsonInputReader)
  File "/*/spert/spert/spert_trainer.py", line 115, in train
    self._eval(model, validation_dataset, input_reader, epoch + 1, updates_epoch)
  File "/*/spert/spert/spert_trainer.py", line 231, in _eval
    for batch in tqdm(sampler, total=total, desc='Evaluate epoch %s' % epoch):
  File "/*/spert/env/lib/python3.6/site-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "/*/spert/spert/sampling.py", line 155, in __next__
    batch, _ = self._results.next()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
RuntimeError: stack expects a non-empty TensorList

**Comment by markus-eberts** [comment]
It looks as if your dev dataset contains samples with empty sentences, i.e. sentences without real tokens. Is this the case? If so, please remove these samples from your dataset.

**Comment by jmlongriver** [comment]
I used the program to check the data to find anything with empty token list, nothing  was found.
then I use the following code  to monitor if the input is empty, but nothing was found, do you have any sense why? 
def _create_eval_sample(doc, max_span_size, context_size):
    encoding = doc.encoding
    token_count = len(doc.tokens)
    if token_count == 0:
        print ("EMPTY TOKENS")
        for token in doc._tokens:
           print (token._phrase)

    # create entity candidates
    entity_spans = []
    entity_masks = []
    entity_sizes = []
    #print ("max:", max_span_size + 1)
    for size in range(1, max_span_size + 1):
        #print ((token_count - size) + 1)
        for i in range(0, (token_count - size) + 1):
            #print ("size:", size)
            #print ("i:", i)
            span = doc.tokens[i:i + size].span
            entity_spans.append(span)
            entity_masks.append(create_entity_mask(*span, context_size))
            entity_sizes.append(size)

    #print ("mask len:", len(entity_masks))
    if len(entity_masks) == 0:
        print ("ZERO ENTITY MASKS")
        for token in doc._tokens:
           print (token._phrase)

**Comment by markus-eberts** [comment]
This is a bit hard to investigate without seeing your dataset. However, the exception "RuntimeError: stack expects a non-empty TensorList" should only occur if the entity_masks list is empty. Are you sure that len(entity_masks) is greater than 0 when the exception occurs? Can you please set 'sampling_processes = 0' in your configuration file, rerun the experiment and send me the output of your print statements when the exception occurs?

**Comment by jmlongriver** [comment]
Thanks for your suggestions, I already figured it out, there are empty tokens.
